import 'package:flutter/material.dart';
import 'package:machinelearningalgorithm/const.dart';
import 'package:machinelearningalgorithm/widget/appbar.dart';
import 'package:machinelearningalgorithm/widget/codeImage.dart';
import 'package:machinelearningalgorithm/widget/heading.dart';
import 'package:machinelearningalgorithm/widget/myDrawer.dart';
import 'package:machinelearningalgorithm/widget/reference.dart';
import 'package:machinelearningalgorithm/widget/text.dart';

class Pandas extends StatelessWidget {
  static const routeName = '/pandas';
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: myAppBar(
          title: "Pandas Intro"
      ),
      drawer: myDrawer(),
      body: SingleChildScrollView(
        child: Container(
          padding: const EdgeInsets.all(8.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
                textbox(text: "In computer programming, pandas is a software library written for the Python programming language for data manipulation and analysis. In particular, it offers data structures and operations for manipulating numerical tables and time series. It is free software released under the three-clause BSD license. Wikipedia"),
              SizedBox(height: 10,),
              Heading(title: "The Ideal tool for data Scientists",),
              textbox(text: "Managing Data"),
              textbox(text: "Cleaning Data"),
              textbox(text: "Analysis"),
              textbox(text: "Modeling data"),
              textbox(text: "Organizing the data in a form suitable for plotting or tabular display"),
              SizedBox(height: 10,),
              Heading(title: "Introduction to panda Data Structure",),
              Divider(),
              textbox(text: "There are there data structure in panda"),
              textbox(text: "Series"),
              textbox(text: "DataFrame"),
              textbox(text: "Panel"),
              Heading(title: "Series",),
              Divider(),
              textbox(text: "A series is a one dimensional array like object containing an array of data(of any numpy data type) and associated array data labels called its index. The simplest series is formed from only an array of data."),
              textbox(text: "a = pd.Series([4,7,3])"),
              Heading(title: "Adding index to the series and extracting data from series by index",),
              Divider(),
              textbox(text: "a = pd.Series([4,7,3],index=[‘a’,’b’,’c’])"),
              textbox(text: "Extracting data from Series"),
              textbox(text: "a[‘a’]"),
              textbox(text: "a[[‘a’,’b’]]"),
              textbox(text: "Convert the python dict to pandas series"),
              textbox(text: "x = {‘a’:10,’b’:30}"),
              textbox(text: "a=pd.series(sdata)"),
              SizedBox(height: 10,),
              Heading(title: "DataFrame",),
              textbox(text: "Python DataFrame is a data structure containing and ordered collections of columns."),
              textbox(text: "Each column may hold numeric, string, Boolean etc. Values"),
              textbox(text: "DataFrame has both row and column index"),
              SizedBox(height: 10,),
              Heading(title: "Creating DataFrame",),
              textbox(text: "A pandas DataFrame can be created using various inputs like"),
              textbox(text: "Lists"),
              textbox(text: "Dict"),
              textbox(text: "Series"),
              textbox(text: "Numpy array"),
              textbox(text: "Anoter DataFrame"),
              SizedBox(height: 10,),
              Heading(title: "Creating Dataframe form list",),
              CodeImage(url: pandasurl+"listtodf.png",),
              SizedBox(height: 10,),
              Heading(title: "Creating DataFrame form dict",),
              CodeImage(url: pandasurl+"listtodf.png",),
              SizedBox(height: 10,),
              Heading(title: "Creating DataFrame form dict",),
              CodeImage(url: pandasurl+"dicttodf.png",),
              SizedBox(height: 10,),
              Heading(title: "Creating DataFrame form list of dict.",),
              CodeImage(url: pandasurl+"ldtodf.png",),
              SizedBox(height: 10,),
              Heading(title: "Creating data from series",),
              CodeImage(url: pandasurl+"stodf.png",),
              SizedBox(height: 10,),
              Heading(title: "Creating data from series",),
              CodeImage(url: pandasurl+"stodf.png",),
              SizedBox(height: 10,),
              Heading(title: "Selection",),
              Divider(),
              Heading(title: "Column Selection",),
              CodeImage(url: pandasurl+"cs.png",),
              SizedBox(height: 10,),
              Heading(title: "Column addition",),
              CodeImage(url: pandasurl+"cad.png",),
              SizedBox(height: 10,),
              Heading(title: "Column Deletion (use del or pop function to delete column)",),
              CodeImage(url: pandasurl+"del.png",),
              SizedBox(height: 10,),
              Heading(title: "Addition of rows",),
              Divider(),
              CodeImage(url: pandasurl+"ra.png",),
              SizedBox(height: 10,),
              Heading(title: "Slice Rows",),
              SizedBox(height: 10,),
              CodeImage(url: pandasurl+"rs.png",),
              SizedBox(height: 10,),
              Heading(title: "Pandas I/O tools"),
              Divider(),
              textbox(text: "The Pandas I/O API is a set of top level reader functions accessed like pd.read_csv() that generally return a Pandas object."),
              textbox(text: "The two functions for reading text files are read_csv() and read_table(). They both intelligently convert tabular data into a DataFrame object"),
              Heading(title: "Read CSV",),
              SizedBox(height: 10,),
              CodeImage(url: pandasurl+"read_csv.png",),
              CodeImage(url: pandasurl+"read_csv_code.png",),
              SizedBox(height: 10,),
              Heading(title: "Utility function",),
              textbox(text: "Sum() : Return the sum of the values for request axis. By default axis=0(column),axis=1(row)"),
              CodeImage(url: pandasurl+"sum.png",),
              SizedBox(height: 10,),
              textbox(text: "Mean(): Return the average value"),
              CodeImage(url: pandasurl+"mean.png",),
              SizedBox(height: 10,),
              textbox(text: "Std():Return the Bressel standard deviation of numerical columns."),
              CodeImage(url: pandasurl+"std.png",),
              SizedBox(height: 10,),
              textbox(text: "Describe(): it summarize the Dataframe statistics."),
              CodeImage(url: pandasurl+"describe.png",),
              Reference(url: ["There are lots of other advance features in pandas you can learn form the pandas official site:\n https://pandas.pydata.org/"],),
              SizedBox(height: 100,),
            ],
          ),
        ),
      ),
    );
  }
}
